import {RippledAmount} from '../objects';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AccountOffersRequest {
  account: string;
  ledger_hash?: string;
  ledger_index?: number | ("validated" | "closed" | "current");
  limit?: number;
  marker?: any;
}

export interface AccountOffersResponse {
  account: string;
  ledger_current_index?: number;
  ledger_index?: number;
  marker?: any;
  offers?: AccountOffer[];
}

export interface AccountOffer {
  flags: number,
  taker_gets: RippledAmount,
  taker_pays: RippledAmount,
  quality: string,
  expiration?: number
}